name: binder
description: binder plugin for flutter
version: 0.0.1
author: WeOS
homepage: 

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: BinderPlugin

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
        